name: Android CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Install Fastlane
        run: |
          gem install bundler:2.4.22
          bundle install

      - name: Run Fastlane Debug Build
        run: |
          bundle exec fastlane debug
